<?php defined("BASEPATH") or exit(); ?>

<section id="desc_section">
   <div class="container">
      <div class="row">
         <div class="col">
            <p class="text-grey">
               This site is not a part of the Youtube, Facebook, Taboola websites or Facebook Inc. Youtube, Alphabet Inc. Additionally, this site is NOT endorsed by Youtube or Facebook, Youtube or Taboola in any way. FACEBOOK is a trademark of FACEBOOK, Inc. Youtube is a trademark of ALPHABET Inc.
               This site and the products and services offered on this site are not associated, affiliated, endorsed, or sponsored by Facebook, Youtube, Taboola or any other social media platforms, nor have they been reviewed, tested, or certified by previously mentioned platforms.
               INCOME DISCLAIMER : This website and the items it distributes contain business strategies, marketing methods and other business advice that, regardless of my own results and experience, may not produce the same results (or any results) for you. AutoBlueprint.net makes absolutely no guarantee, expressed or implied, that by following the advice or content available from this web site you will make any money or improve current profits, as there are several factors and variables that come into play regarding any given business. Primarily, results will depend on the nature of the product or business model, the conditions of the marketplace, the experience of the individual, and situations and elements that are beyond your control. As with any business endeavor, you assume all risk related to investment and money based on your own discretion and at your own potential expense.
               LIABILITY DISCLAIMER: By reading this website or the documents it offers, you assume all risks associated with using the advice given, with a full understanding that you, solely, are responsible for anything that may occur as a result of putting this information into action in any way, and regardless of your interpretation of the advice. You further agree that our company cannot be held responsible in any way for the success or failure of your business as a result of the information provided by our company. It is your responsibility to conduct your own due diligence regarding the safe and successful operation of your business if you intend to apply any of our information in any way to your business operations. In summary, you understand that we make absolutely no guarantees regarding income as a result of applying this information, as well as the fact that you are solely responsible for the results of any action taken on your part as a result of any given information. In addition, for all intents and purposes you agree that our content is to be considered “for entertainment purposes only”. Always seek the advice of a professional when making financial, tax or business decisions.
               © 2022 ALL RIGHTS RESERVED. UNAUTHORIZED DUPLICATION OR PUBLICATION OF ANY MATERIALS FROM THIS SITE IS EXPRESSLY PROHIBITED. ALL PRODUCT NAMES, LOGOS, AND BRANDS ARE PROPERTY OF THEIR RESPECTIVE OWNERS. ALL COMPANY, PRODUCT AND SERVICE NAMES USED IN THIS WEBSITE ARE FOR IDENTIFICATION PURPOSES ONLY. USE OF THESE NAMES, LOGOS, AND BRANDS DOES NOT IMPLY ENDORSEMENT. THE VIEWS AND INFORMATION CONTAINED WITHIN THIS WEBSITE ARE PROVIDED FOR INFORMATIONAL PURPOSES ONLY, ARE NOT MEANT AS FINANCIAL ADVICE, AND REPRESENT THE CURRENT GOOD-FAITH VIEWS OF THE AUTHORS AT THE TIME OF PUBLICATION. THE ABOVE STATEMENTS ARE A REPRESENTATION OF VENDOR’S EXPERIENCES. EVERY EFFORT HAS BEEN MADE TO ACCURATELY REPRESENT THIS PRODUCT AND ITS POTENTIAL. EXAMPLES AND TESTIMONIALS IN THESE MATERIALS ARE NOT TO BE INTERPRETED AS A PROMISE OR GUARANTEE OF RESULTS. THIS PRODUCT’S POTENTIAL IS ENTIRELY DEPENDENT ON THE PERSON USING IT, AND THEIR CURRENT SITUATION. AutoBlueprint <a href="/login" class="text-white">Login</a>
            </p>
         </div>
      </div>
</section>